import "@radix-ui/themes/styles.css";
import "./globals.css";
import './theme-config.css'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {Container, Theme} from "@radix-ui/themes";
import NavBar from "@/app/NavBar";
import AuthProvider from "@/app/auth/Provider";
import QueryClientProvider from "@/app/QueryClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <QueryClientProvider>
          <AuthProvider>
              <Theme accentColor="sky" radius="large">
                  <NavBar/>
                  <main className='p-5'>
                      <Container>
                          {children}
                      </Container>
                  </main>
              </Theme>
          </AuthProvider>
      </QueryClientProvider>
      </body>
    </html>
  );
}
